name = "PineScript"
grammar = "pinescript"
path_suffixes = ["pine", "ps", "pinescript"]
line_comments = ["// "]
tab_size = 4
hard_tabs = false
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false },
]
